version: '3'
services:
  client:
    depends_on:
      - api
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - '3000:3000'
  api:
    build: 
      dockerfile: Dockerfile
      context: ./backend
    environment:
      - PORT=5000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}